# Makefile generated by luasnip
CC = g++
CFLAGS = -Wall -Werror -lraylib
TARGET = game
SRCS = main.cpp
OBJS = $(SRCS:.cpp=.o)
all: $(TARGET)
	$(CC) $(CFLAGS) -o $(TARGET) $(OBJS)

$(TARGET): $(OBJS)
	$(CC) $(CFLAGS) -o $@ $^

%.o: %.cpp
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJS) $(TARGET)

